name: Challenge-CD

on:
  push:
    branches:
      - main
    paths:
      - 'kube/**'
  workflow_dispatch:
    
jobs:     
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.K8S_CONFIG }}
        version: "latest"
    - name: Deploy to MicroK8s
      run: |
        kubectl apply -f ./kube/deploy.yaml
      
